version: '2'

services:
  musicbot-example:
    restart: unless-stopped
    image: rafaelsgirao/jmusicbot-docker
    #I recommend an instance per server so each bot can have a working 'Now playing' status msg
    container_name: musicbot_example
    build: .
    volumes:
      - type: bind
        source: ./config-example.txt
        target: /config/config.txt

